#version: '0'

services:
#  zookeeper:
#    image: zookeeper:3.7
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zookeeper:2888:3888
#
#  kafka:
#    image: confluentinc/cp-kafka:7.3.0
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zookeeper

#  app-order-service:
#    depends_on:
#      - cassandra
#    build:
#      context: ./order-service
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - '8084:8084'
#    volumes:
#      - ~/.m2:/root/.m2
#    stdin_open: true
#    tty: true




#  web:
#    build:
#      context: ./react
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  cassandra-load-keyspace:
    image: cassandra:latest
    container_name: cassandra-load-keyspace
    depends_on:
      - cassandra

    volumes:
      - ./init-scripts/init-cassandra.cql:/init-cassandra.cql
    command: /bin/bash -c "sleep 100 && echo loading cassandra keyspace && cqlsh cassandra -f /init-cassandra.cql"

  account-mysql:
    image: mysql:latest
    container_name: account-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "0424"
      MYSQL_DATABASE: amall
    ports:
      - "13306:3306"
    volumes:
      - account-mysql-data:/var/lib/mysql  # Volume for data persistence
    restart: always  # Restart policy

  cart-mysql:
    image: mysql:latest
    container_name: cart-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "0424"
      MYSQL_DATABASE: amall
    ports:
      - "13307:3306"
    volumes:
      - cart-mysql-data:/var/lib/mysql  # Volume for data persistence
    restart: always  # Restart policy

volumes:
  cassandra-data:
  account-mysql-data:
  cart-mysql-data:
