version: '0'

services:
#  app-order-service:
#    depends_on:
#      - cassandra
#    build:
#      context: ./order-service
#      dockerfile: Dockerfile
#    restart: on-failure
#    ports:
#      - '8084:8084'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true



  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./react:/app

  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  cassandra-load-keyspace:
    image: cassandra:latest
    container_name: cassandra-load-keyspace
    depends_on:
      - cassandra

    volumes:
      - ./init-scripts/init-cassandra.cql:/init-cassandra.cql
    command: /bin/bash -c "sleep 100 && echo loading cassandra keyspace && cqlsh cassandra -f /init-cassandra.cql"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "0424"
      MYSQL_DATABASE: amall
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Volume for data persistence
    restart: always  # Restart policy

volumes:
  cassandra-data:
  mysql-data: