server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的地址
  instance:
    ip-address: localhost
    prefer-ip-address: true  # 使用 IP 地址而不是主机名注册

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v0/accounts/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v0/orders/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/api/v0/items/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v0/carts/**

amall:
  jwt:
    location: classpath:amall.jks
    alias: amall
    password: amall123
    tokenTTL: 30m
  auth:
    excludePaths:
#      - /api/v0/search/**
      - /api/v0/accounts/user/login
      - /api/v0/accounts/user/signup