server:
  port: 8085

spring:
  application:
    name: kafka-service
  profiles:
    active: dev


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的地址
  instance:
    ip-address: localhost
    prefer-ip-address: true  # 使用 IP 地址而不是主机名注册
