server:
  port: 8084

spring:
  application:
    name: order-service
  profiles:
    active: dev
  cassandra:
    keyspace-name: order_keyspace
    contact-points: 127.0.0.1
    port: 9042
    schema-action: recreate
#    schema-action: create_if_not_exists
    local-datacenter: datacenter1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的地址
  instance:
    ip-address: localhost
    prefer-ip-address: true  # 使用 IP 地址而不是主机名注册
