server:
  port: 8084

spring:
  application:
    name: order-service
  profiles:
    active: dev
  cassandra:
    contact-points: localhost
    port: 9042
    username: admin
    password: admin
    schema-action: update