server:
  port: 8083

spring:
  application:
    name: item-service # 微服务名称
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://aierken103:a123456@cluster0.gxpsiii.mongodb.net/<your-database-name>?retryWrites=true&w=majority&appName=Cluster0
