server:
  port: 8083

spring:
  application:
    name: item-service # 微服务名称
  profiles:
    active: dev
  data:
    mongodb:
      host: localhost
      port: 13307
      database: amall
      username: root
      password: '0424'