server:
  port: 8083

spring:
  application:
    name: item-service # 微服务名称
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://FinalProject:test1234@cluster0.mxi8i1m.mongodb.net/OnlineShopping

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 的地址
  instance:
    ip-address: localhost
    prefer-ip-address: true  # 使用 IP 地址而不是主机名注册