server:
  port: 8083

spring:
  application:
    name: item-service # 微服务名称
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://FinalProject:test1234@cluster0.mxi8i1m.mongodb.net/OnlineShopping
